service: mm-afterwork
package:
  include:
    - afterwork.py
    - packages

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  profile: personal

functions:
  placesuggester:
    environment:
      authKey: ${file(./conf.yml):authKey}
      googleMapsApiKey: ${file(./conf.yml):googleMapsApiKey}
    handler: suggester.index
    events:
      - http:
          path: placessuggester
          method: post
          integration: lambda
          request:
            template:
              application/json: ${file(./s-templates.s)}
  afterwork:
    environment:
      authKey: ${file(./conf.yml):authKey}
      botName: ${file(./conf.yml):botName}
      channelName: ${file(./conf.yml):channelName}
      tableName: afterworks
      googleMapsApiKey: ${file(./conf.yml):googleMapsApiKey}
    handler: handler.index
    events:
      - http:
          path: afterwork
          method: post
          integration: lambda
          request:
            template:
              application/json: ${file(./s-templates.s)}
      - schedule:
          rate: cron(0 12 ? * MON-FRI *)
          enabled: true
          input:
            triggerToken: ${file(./conf.yml):authKey}
  afterworkAuthorizer:
    environment:
      authKey: ${file(./conf.yml):authKey}
      botName: ${file(./conf.yml):botName}
      channelName: ${file(./conf.yml):channelName}
      tableName: afterworks
      googleMapsApiKey: ${file(./conf.yml):googleMapsApiKey}
      clientId: ${file(./conf.yml):clientId}
      clientSecret: ${file(./conf.yml):clientSecret}
    handler: handler.authorize
    events:
      - http:
          path: afterwork
          method: get
          integration: lambda


resources:
  Resources:
    AuthorizedUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: authorizedApps
        AttributeDefinitions:
          -
            AttributeName: "TeamId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "TeamId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "2"
          WriteCapacityUnits: "2"
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: afterworks
        AttributeDefinitions:
          -
            AttributeName: "Date"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "Date"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "2"
          WriteCapacityUnits: "2"
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource: arn:aws:dynamodb:*:*:table/afterworks
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource: arn:aws:dynamodb:*:*:table/authorizedApps
        Roles:
          - Ref: IamRoleLambdaExecution
