service: mm-afterwork
package:
  include:
    - afterwork.py

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1

functions:
  afterwork:
    environment:
      apiKey: ${file(./conf.yml):apiKey}
    handler: handler.index
    events:
      - http:
          path: afterwork
          method: post
          integration: lambda
          request:
            template:
              application/json: ${file(./s-templates.s)}

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "afterworks"
        AttributeDefinitions:
          -
            AttributeName: "Date"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "Date"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "2"
          WriteCapacityUnits: "2"
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource: arn:aws:dynamodb:*:*:table/afterworks
        Roles:
          - Ref: IamRoleLambdaExecution